### PR TITLE
New: Add latest memgraph-platform version with Dockerfile fixes

### PR DESCRIPTION
**Pull request by tonilastre**
it contains the following updates:

* Use the latest `memgraph-platform` image
* Setting logs to `INFO`
* Use default static `index.html` as a proxy to Memgraph Lab listening on `:3000`

### CODE REVIEW

**Comment by lucidhive** [comment]
Hey looks great, tried to install on docker desktop MAC latest as of today and it wouldnt install via UI. Tried manual install and came upon 2 issues.

1. Image Platform = 
Extracting metadata and files for the extension "ajeetraina/memgraph-docker-extension:latest"

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested

2. 
Will try again after disabling Grafana which runs on Port:3000 

Extension "Memgraph" removed
installation could not be completed due to: executing 'docker --context desktop-linux compose -p ajeetraina_memgraph-docker-extension-desktop-extension -f extensions/ajeetraina_memgraph-docker-extension/vm/docker-compose.yaml up -d' : exit status 1: 
Network ajeetraina_memgraph-docker-extension-desktop-extension_default  Creating
Network ajeetraina_memgraph-docker-extension-desktop-extension_default  Created
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_log"  Creating
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_log"  Created
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_etc"  Creating
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_etc"  Created
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_lib"  Creating
Volume "ajeetraina_memgraph-docker-extension-desktop-extension_mg_lib"  Created
Container ajeetraina_memgraph-docker-extension-desktop-extension-service  Creating
Container ajeetraina_memgraph-docker-extension-desktop-extension-service  Created
Container ajeetraina_memgraph-docker-extension-desktop-extension-service  Starting
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:3000 -> 0.0.0.0:0: listen tcp 0.0.0.0:3000: bind: address already in use

**Comment by tonilastre** [comment]
@lucidhive thanks for checking it out.

Regarding issue number 1 - Hmm, do I need to have some additional configuration or Docker should handle that on its end? For example the `memgraph-platform` image tag that was used ([Docker hub link](https://hub.docker.com/layers/memgraph/memgraph-platform/2.6.6-memgraph2.6.0-lab2.5.0-mage1.6.1/images/sha256-b634d7375b995481b1122e4f1e2e912812faa0284297b115a3a44c1cba3fb5c6?context=explore)) has both `linux/arm64` and `linux/amd64`?

For issue number 2 - Yep, looks like a port conflict. I thought the docker-compose network should handle that because I am sure there will be other port conflicts when using N different extensions. What do you think?

**Comment by ajeetraina** [comment]
@lucidhive Can we push this issue thread to https://github.com/collabnix/memgraph-docker-extension/issues?
That's better place to discuss it.

**Comment by ajeetraina** [comment]
@lucidhive You can directly run the command to get it up and running:

```
docker extension install ajeetraina/memgraph-docker-extension:2.6.0
```

**Pull request merged**
